### PR TITLE
Fixed all your mistakes

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**
# How to use a pull request
### Pull requests are requests for merging branches.

Just like I forked your repository and fixed all the mistakes for you, and you can see what I changed in here. You can either accept or reject this pull request. If this pull request is accepted, my changes will be applied to the main branch od this repository!

# Pull after merging
Please press the pull or fetch option / button in your git client, this will apply the merged changes to the repository on your iPad's local disk.

### CODE REVIEW

**Comment by Endermanbugzjfc** [comment]
### Since you edited your file again before I create this pull request, there's are conflicting files.
You can resolve the conflicts here.

**Comment by Teunboeke** [comment]
Test

**Comment by mmm545** [comment]
Test

**Comment by Endermanbugzjfc** [comment]
Test

**Review by Teunboeke — APPROVED** [review]

**Review by Teunboeke — APPROVED** [review]

**Comment by mmm545** [comment]
did you just approve a pull request two times?

**Comment by mmm545** [comment]
the pr hasn't been merged oof

**Comment by Endermanbugzjfc** [comment]
the pr hasn't been merged oof

**Pull request closed without merging**
